"use client";

import { useState } from "react";
import { askPostQuestion } from "@/lib/api-client";
import { SparklesIcon, PaperAirplaneIcon } from "@heroicons/react/24/solid";

interface AskAyoolaWidgetProps {
  postId: string;
}

export default function AskAyoolaWidget({ postId }: AskAyoolaWidgetProps) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setError("");
    setAnswer("");

    try {
      const result = await askPostQuestion(postId, question);
      setAnswer(result.answer);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      if (msg.includes("503") || msg.includes("overloaded")) {
        setError(
          "I'm currently overloaded with requests. Please give me a moment and try again.",
        );
      } else if (msg.includes("429") || msg.includes("Rate Limit")) {
        setError(
          "I've received too many requests recently. Please wait a moment.",
        );
      } else if (msg.includes("500") || msg.includes("Internal Server Error")) {
        setError(
          "I encountered a temporary glitch. Please try asking again in a few seconds.",
        );
      } else {
        setError("Failed to get an answer. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="my-12 border border-yellow-500/20 rounded-xl bg-neutral-900/50 overflow-hidden">
      <div className="p-4 md:p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 bg-yellow-500/10 rounded-lg">
            <SparklesIcon className="w-6 h-6 text-yellow-500" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-neutral-100">
              Ask Ayoola AI
            </h3>
            <p className="text-sm text-neutral-400">
              Curious? Ask my digital twin anything about this post!
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="relative">
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g., What's the main takeaway? or How does this apply to me?"
            className="w-full bg-black border border-neutral-800 rounded-lg py-3 pl-4 pr-12 text-neutral-200 placeholder-neutral-600 focus:outline-none focus:border-yellow-500/50 focus:ring-1 focus:ring-yellow-500/50 transition-all"
            disabled={loading}
          />
          <button
            type="submit"
            disabled={loading || !question.trim()}
            className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-yellow-500 hover:text-yellow-400 disabled:text-neutral-700 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? (
              <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin" />
            ) : (
              <PaperAirplaneIcon className="w-5 h-5" />
            )}
          </button>
        </form>

        {error && (
          <div className="mt-4 p-3 bg-red-900/20 border border-red-900/50 rounded-lg text-red-400 text-sm">
            {error}
          </div>
        )}

        {answer && (
          <div className="mt-6 animate-fade-in-up">
            <div className="bg-neutral-800/50 rounded-lg p-4 border-l-4 border-yellow-500">
              <p className="text-neutral-300 leading-relaxed text-sm md:text-base">
                {answer}
              </p>
              <div className="mt-3 flex items-center justify-end">
                <span className="text-xs text-neutral-500 font-mono">
                  Generated by Ayoola AI
                </span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
